version: "3.3"

services:
  portfolio-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-site:0.1.2
    ports:
      - "9842:3000"

    pull_policy: build
    restart: always
